---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.50.240-192.168.50.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-advert
  namespace: metallb-system
