version: "2"

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.8
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - "rabbitmq_data:/bitnami"

  postgresql:
    image: docker.io/bitnami/postgresql:11
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"

volumes:
  rabbitmq_data:
    driver: local
  postgresql_data:
    driver: local
