---
- name: update ca certs
  command: update-ca-certificates --fresh

- name: reconfigure gitlab
  command: gitlab-ctl reconfigure

- name: copy root password
  fetch:
    src: /etc/gitlab/initial_root_password
    dest: "{{ playbook_dir }}/../gitlab-root-password"
    flat: yes
