---
- name: update ca certs
  command: update-ca-certificates --fresh

- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart gitlab runner
  service:
    name: gitlab-runner
    state: restarted
