---
- name: Create Gitlab admin service account YAML
  copy:
    src: roles/k8s/files/gitlab-admin-service-account.yaml
    dest: /home/vagrant/gitlab-admin-service-account.yaml
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Create Gitlab admin service account in Kubernetes
  shell: "kubectl apply -f gitlab-admin-service-account.yaml > gitlab-admin.txt"
  become: no
  args:
    chdir: $HOME
    creates: gitlab-admin.txt

- name: Get Gitlab admin account token
  shell: "{% raw %}kubectl -n kube-system get secret $(kubectl -n kube-system get secret | grep gitlab | awk '{ print $1 }') -o 'go-template={{ index .data.token | base64decode }}'{% endraw %}"
  become: no
  register: gitlab_admin_account_token_raw

- name: Write Gitlab admin token to file
  copy:
    content: "{{ gitlab_admin_account_token_raw.stdout_lines[0] }}"
    dest: /home/vagrant/gitlab-admin-token
    owner: vagrant
    group: vagrant
    mode: 0600

- name: Get Kubernetes CA certificate
  shell: "{% raw %}kubectl get secrets -o name | grep -E '^secret/default-token-\\w+' | xargs kubectl get -o 'go-template={{ index .data \"ca.crt\" | base64decode }}'{% endraw %}"
  become: no
  register: k8s_ca_certificate_raw

- name: Write Kubernetes CA certificate to file
  copy:
    content: "{{ k8s_ca_certificate_raw.stdout_lines | join('\n') }}"
    dest: /home/vagrant/k8s-ca-certificate
    owner: vagrant
    group: vagrant
    mode: 0600

- name: Download Gitlab admin token
  fetch:
    src: /home/vagrant/gitlab-admin-token
    dest: "{{ playbook_dir }}/../../vagrant-gitlab/provisioning/roles/gitlab-ce/files/gitlab-k8s-admin-token"
    flat: yes

- name: Download Kubernetes CA certificate
  fetch:
    src: /home/vagrant/k8s-ca-certificate
    dest: "{{ playbook_dir }}/../../vagrant-gitlab/provisioning/roles/gitlab-ce/files/k8s-ca-certificate"
    flat: yes

- name: Get Gitlab Prometheus values YAML
  get_url:
    url: https://gitlab.com/gitlab-org/project-templates/cluster-management/-/raw/master/applications/prometheus/values.yaml
    dest: /home/vagrant/gitlab-prometheus-values.yaml
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Add Prometheus Helm repository
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  become: no

- name: Deploy Prometheus for Gitlab
  command: helm upgrade --install prometheus prometheus-community/prometheus -n gitlab-managed-apps --create-namespace --values gitlab-prometheus-values.yaml
  become: no