---
- name: Install Helm
  command: snap install helm --classic

- name: Initialise the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address=192.168.50.10 --apiserver-cert-extra-sans=192.168.50.10 --node-name k8s-master --pod-network-cidr=192.168.0.0/16
  args:
    creates: /var/lib/kubelet/config.yaml

- name: Create Kubernetes configuration directory for the vagrant user
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: 0700
    owner: vagrant
    group: vagrant

- name: Copy the kubeconfig into vagrant's configuration directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: 0600

# Configure a CNI plugin, Calico in this case.
- name: Install Calico pod network
  shell: "kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml > cni-setup.txt"
  become: no
  args:
    chdir: $HOME
    creates: cni-setup.txt

# Record the join command for use on nodes.
- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Copy kubeconfig to host
  fetch:
    src: /home/vagrant/.kube/config
    dest: "{{ playbook_dir }}/../kubeconfig"
    flat: yes
  become: no
