---
- name: re-export nfs
  command: exportfs -ra

- name: update ca certs
  command: update-ca-certificates --fresh

- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: generate locales
  command: locale-gen
