---
- name: Install prerequisites
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - curl
      - debian-archive-keyring
      - gnupg-agent

- name: Create CA certificate directory
  file:
    path: /usr/local/share/ca-certificates/easyrsa
    state: directory
    mode: 0755

- name: Copy CA certificate
  copy:
    src: roles/common/files/ca.crt
    dest: /usr/local/share/ca-certificates/easyrsa/ca.crt

- name: Add CA certificate to system store
  lineinfile:
    path: /etc/ca-certificates.conf
    regexp: '^easyrsa/ca\.crt$'
    line: 'easyrsa/ca.crt'
    state: present
  notify:
    - update ca certs

- name: Flush handlers
  meta: flush_handlers

- name: Add apt signing key for Gitlab Runner
  apt_key:
    url: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
    state: present

- name: Add Gitlab Runner apt repository
  apt_repository:
    repo: deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ focal main
    state: present
    filename: gitlab-runner

- name: Install Gitlab Runner
  apt:
    name: gitlab-runner
    state: present
    update_cache: yes

- name: Configure Gitlab Runner
  template:
    src: roles/gitlab-runner/templates/config.toml.tpl
    dest: /etc/gitlab-runner/config.toml
    mode: 0600
  notify:
    - restart gitlab runner

- name: Remove loopback hostname from /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\..*{{ ansible_nodename }}\s+{{ ansible_nodename }}$'
    state: absent

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ item["ip"] | regex_escape() }}\s+{{ item["fqdn"] | regex_escape() }}\s+{{ item["fqdn"].split(".")[0] }}$'
    line: '{{ item["ip"] }} {{ item["fqdn"] }} {{ item["fqdn"].split(".")[0] }}'
    state: present
  with_items:
    - ip: 192.168.50.50
      fqdn: gitlab.example.com
    - ip: 192.168.50.51
      fqdn: gitlab-runner.example.com

- name: Add apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Install Docker and company
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create Docker certificate trust directory
  file:
    path: /etc/docker/certs.d/gitlab.example.com:5050
    state: directory
    mode: 0755

- name: Copy the CA certificate to the Docker trust directory
  copy:
    src: roles/common/files/ca.crt
    dest: /etc/docker/certs.d/gitlab.example.com:5050/ca.crt
    mode: 0644
  notify:
    - restart docker
